INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0100','ESTIBADOR1','20221214',NULL,NULL,'','1','1','1','1','1','1','1',NULL)
INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0101','ESTIBADOR1','20221214',NULL,NULL,'','1','1','1','1','1','1','1',NULL)
INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0106','ESTIBADOR1','20221214',NULL,NULL,'','1','1','1','1','1','1','1',NULL)
INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0107','ESTIBADOR1','20230103',NULL,NULL,'','1','1','1','1','1','1','1',NULL)
INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0108','ESTIBADOR1','20230324',NULL,NULL,'','1','1','1','1','1','1','1',NULL)
INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0197','ESTIBADOR1','20230103',NULL,NULL,'','1','1','1','1','1','1','1',NULL)
INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0198','ESTIBADOR1','20230103',NULL,NULL,'','1','1','1','1','1','1','1',NULL)
INSERT INTO [assusuariosistemamenu] ([c_codigo_usu],[c_codigo_sis],[c_codigo_sme],[c_usucre_usm],[d_creacion_usm],[c_usumod_usm],[d_modifi_usm],[c_activo_usm],[c_nuevo_usm],[c_editar_usm],[c_eliminar_usm],[c_recuperar_usm],[c_imprimir_usm],[c_mostrareliminados_usm],[c_exportar_usm],[c_codigo_per])VALUES('ADMIN','70','0199','ESTIBADOR1','20230103',NULL,NULL,'1','1','1','1','1','1','1','1',NULL)


--SELECT * FROM  dbo.assusuario
--WHERE c_codigo_usu='ESTIBADOR1          '